language: java

install: echo "I trust Maven."

env:
  global:
     - secure: "rT6NzwhBiT1Ybvuuq5NfK0GZQ0woRHAXVaHCSRd7emJLa6lu/l7Vfit7qOIgB36RFLW23p0cFqcFmE1ewC9IE/xUnyvGmTvUBazeD8/u0VUYYV2fGDwP7yhVMf/pZbKTpbX6mjegLd0RYiLMvIK5fCRvy+op+3lrX/XYrPpAY24="

# don't just run the tests, also run Findbugs and friends
script: mvn verify coveralls:jacoco

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

notifications:
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email:
    recipients:
      - wrey75@gmail.com
